name: Feature request
description: Suggest an idea
title: "[feat] "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What do you want to add/change?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is it useful?
